apiVersion: v1
kind: PersistentVolume
metadata:
  name: nombre-disco-persistente
spec:
  storageClassName: ""
  capacity:
    storage: 10G #tamaño del volumen
  accessModes:
    - ReadWriteMany #Tipo de acceso al disco, hay mas opciones
  gcePersistentDisk:
    pdName: pd-cluster #nombre del disco persistente alojado en GCP (google cloud)
    fsType: ext4 # FileSystem type
    
--- #Aqui se separan dos yaml en un mismo archivo

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nombre-persistent-volumen-claim
spec:
  # It's necessary to specify "" as the storageClassName
  # so that the default storage class won't be used, see
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  storageClassName: ""
  volumeName: nombre-disco-persistente #en este caso "nombre-disco-persistente"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G #tamaño a utilizar a partir del persistentVolume
